1

diff --git a/.github/workflows/python-app.yml b/.github/workflows/python-app.yml
--- a/.github/workflows/python-app.yml
+++ b/.github/workflows/python-app.yml
@@ -22,7 +22,7 @@ jobs:
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
-        pip install flake8 pytest
+        pip install flake8 pytest pytest-json
         if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
     - name: Lint with flake8
       run: |
@@ -30,8 +30,16 @@ jobs:
         flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
     - name: Test with pytest
       run: |
-        pytest --json=results.json
+        pytest --json=results.json || { echo "pytest failed"; exit 1; }
       continue-on-error: true
+    - name: Check if results.json exists
+      run: |
+        if [ -f results.json ]; then
+          echo "results.json exists"
+        else
+          echo "results.json does not exist"
+          exit 1
+        fi
     - name: Generate badge URL
       id: badge
       run: |
